import type { GlossaryRecord, TechnologyRecord } from "./types";
import { REVIEW_DATE } from "./workflow-content";

const tech = (
  id: string,
  name: string,
  category: string,
  level: TechnologyRecord["level"],
  what: string,
  pros: string[],
  cons: string[],
  chooseWhen: string,
  avoidWhen: string,
  source: TechnologyRecord["source"],
  volatility: TechnologyRecord["volatility"] = "changing",
): TechnologyRecord => ({
  id,
  name,
  category,
  level,
  what,
  pros,
  cons,
  chooseWhen,
  avoidWhen,
  source,
  reviewedAt: REVIEW_DATE,
  volatility,
  claimType: "engineering-judgment",
});

export const TECHNOLOGIES: TechnologyRecord[] = [
  tech(
    "html-css-js",
    "HTML / CSS / JavaScript",
    "Web 基础",
    "core",
    "浏览器原生支持的结构、样式与行为技术，是其他前端框架的基础。",
    ["标准、可移植、依赖少", "适合内容型和小型交互网站", "学习后能理解框架实际做了什么"],
    ["复杂状态和大型组件协作需要自行建立约定", "重复页面容易产生维护成本"],
    "页面少、交互简单、希望长期可打开或需要单 HTML 时。",
    "多人长期开发复杂应用，却没有组件、类型和测试约定时。",
    { label: "MDN · Web 技术", url: "https://developer.mozilla.org/docs/Web" },
    "stable",
  ),
  tech(
    "typescript",
    "TypeScript",
    "Web 基础",
    "core",
    "在 JavaScript 上增加静态类型检查，并编译为 JavaScript。",
    ["更早发现接口和数据形状错误", "编辑器提示更完整", "适合 AI 修改后的快速反馈"],
    ["增加配置和类型建模成本", "类型通过不等于业务正确"],
    "项目会持续演进、多人协作或数据契约较多时。",
    "一次性、极小的无构建脚本，且类型配置成本超过收益时。",
    { label: "TypeScript 官方文档", url: "https://www.typescriptlang.org/docs/" },
  ),
  tech(
    "git-github",
    "Git + GitHub",
    "工程基础",
    "core",
    "Git 记录代码历史；GitHub 托管仓库并提供协作、评审与自动化能力。",
    ["可追踪和恢复改动", "便于 AI 只评审差异", "支持分支、PR 和 CI"],
    ["错误的密钥提交会进入历史", "分支与冲突需要基本操作纪律"],
    "任何需要持续维护、协作或上线的网站。",
    "不应避免；即使单人项目也建议使用版本控制。",
    { label: "GitHub Docs · Get started", url: "https://docs.github.com/get-started" },
    "stable",
  ),
  tech(
    "astro",
    "Astro",
    "前端框架",
    "core",
    "面向内容网站的 Web 框架，默认尽量少向浏览器发送 JavaScript，并可按需加入交互组件。",
    ["适合官网、博客和文档", "静态输出简单", "可逐步引入 React/Vue 等组件"],
    ["复杂应用状态不是主要长项", "团队仍需理解构建与内容模型"],
    "内容为主、性能和代码所有权重要，交互相对局部时。",
    "核心价值依赖大量登录后状态、实时交互或统一 React 生态时。",
    { label: "Astro 官方文档", url: "https://docs.astro.build/" },
  ),
  tech(
    "nextjs",
    "Next.js",
    "前端框架",
    "core",
    "基于 React 的全栈 Web 框架，提供路由、渲染、数据获取和服务端能力。",
    ["React 生态完整", "静态与动态页面可共存", "适合逐步发展为 Web App"],
    ["概念和部署面比纯静态方案多", "错误的数据边界会把复杂度带到客户端和服务端"],
    "需要登录、服务端逻辑、动态数据或团队熟悉 React 时。",
    "只是少量稳定内容页面，且运营希望完全可视化维护时。",
    { label: "Next.js 官方文档", url: "https://nextjs.org/docs" },
  ),
  tech(
    "react",
    "React",
    "前端库",
    "core",
    "用于通过组件构建用户界面的 JavaScript 库。",
    ["组件生态大", "适合复杂交互", "与多种框架和设计系统兼容"],
    ["不是完整建站方案", "状态、路由、数据和性能仍需架构判断"],
    "界面交互复杂、团队已有 React 经验或所选框架基于 React 时。",
    "静态页面不需要额外客户端运行时，或团队只为跟风引入时。",
    { label: "React 官方文档", url: "https://react.dev/" },
  ),
  tech(
    "vue-nuxt",
    "Vue / Nuxt",
    "前端框架",
    "advanced",
    "Vue 是渐进式界面框架；Nuxt 在其上提供完整的应用与服务端渲染能力。",
    ["模板语法对部分新手直观", "从局部交互到完整应用均有路径", "Nuxt 提供较完整约定"],
    ["与 React 生态的组件和人才不可直接互换", "仍需处理状态、服务端和部署边界"],
    "团队熟悉 Vue，或现有组件与内容体系基于 Vue/Nuxt 时。",
    "团队和依赖均以 React 为主，只为尝鲜切换时。",
    { label: "Nuxt 官方文档", url: "https://nuxt.com/docs" },
  ),
  tech(
    "vite",
    "Vite",
    "构建工具",
    "advanced",
    "现代前端开发服务器与构建工具，可供多种框架使用。",
    ["开发反馈快", "配置生态成熟", "适合静态前端和组件应用"],
    ["不是路由、CMS 或后端", "选择 Vite 仍需决定应用架构"],
    "需要轻量前端构建、框架模板或库开发时。",
    "误把它当成能独立解决内容、数据和部署的完整方案时。",
    { label: "Vite 官方文档", url: "https://vite.dev/guide/" },
  ),
  tech(
    "tailwind",
    "Tailwind CSS",
    "样式系统",
    "advanced",
    "通过工具类在标记中组合样式的 CSS 框架。",
    ["设计令牌和响应式写法集中", "组件中修改样式反馈快", "适合有明确组件边界的团队"],
    ["类名密度高", "没有设计约束时仍会产生不一致", "并不替代语义 HTML 和可访问性"],
    "团队接受工具类，并有组件/令牌规范时。",
    "内容作者直接编辑 HTML，或项目只需很少样式时。",
    { label: "Tailwind CSS 官方文档", url: "https://tailwindcss.com/docs" },
  ),
  tech(
    "shadcn",
    "shadcn/ui",
    "组件方案",
    "advanced",
    "把可修改的组件源码加入项目，而不是提供传统封装依赖的组件分发方式。",
    ["代码所有权高", "适合快速建立 React UI 基线", "能按品牌和业务深改"],
    ["加入项目后维护责任属于你", "视觉同质化风险高", "仍需做内容和流程设计"],
    "React 项目需要可修改组件起点，并愿意维护源码时。",
    "非 React 项目，或团队希望供应商完全托管组件升级时。",
    { label: "shadcn/ui 官方文档", url: "https://ui.shadcn.com/docs" },
  ),
  tech(
    "wordpress",
    "WordPress",
    "CMS / 建站",
    "core",
    "开源内容管理系统，可通过主题和插件构建网站。",
    ["编辑后台成熟", "内容团队容易找到经验", "生态广"],
    ["插件和主题会扩大安全与维护面", "性能和一致性取决于组合质量", "复杂定制容易累积债务"],
    "运营频繁更新内容，且团队有 WordPress 维护能力时。",
    "追求极少维护、极小攻击面，或复杂应用逻辑不适合插件堆叠时。",
    { label: "WordPress 官方文档", url: "https://wordpress.org/documentation/" },
  ),
  tech(
    "webflow",
    "Webflow",
    "可视化建站",
    "core",
    "带可视化设计、CMS 和托管能力的商业建站平台。",
    ["设计与发布一体", "运营可直接编辑", "适合营销型网站快速迭代"],
    ["平台能力、价格和导出边界会变化", "复杂业务逻辑受平台约束", "迁移需要提前验证"],
    "视觉编辑和快速营销发布比完全代码控制更重要时。",
    "核心业务需要复杂权限、交易或严格可迁移后端时。",
    { label: "Webflow 官方文档", url: "https://help.webflow.com/" },
  ),
  tech(
    "framer",
    "Framer",
    "可视化建站",
    "core",
    "面向设计和营销网站的可视化制作与托管工具。",
    ["原型到发布路径短", "适合落地页和作品集", "非开发者可维护部分内容"],
    ["复杂数据与业务流程能力有限", "代码和迁移边界需要单独核验"],
    "小型营销站、作品集或活动页，且视觉速度优先时。",
    "登录后应用、复杂电商或长期平台级扩展时。",
    { label: "Framer 官方帮助", url: "https://www.framer.com/help/" },
  ),
  tech(
    "shopify",
    "Shopify",
    "电商",
    "core",
    "托管式商业平台，覆盖商品、订单、支付生态与店铺运营。",
    ["常见电商能力成熟", "减少自建支付与订单基础设施", "运营工具完整"],
    ["平台费用和扩展边界需持续核验", "深度定制可能依赖应用生态", "跨地区支付与合规需另评估"],
    "标准商品零售，希望先用成熟交易平台验证业务时。",
    "业务不是标准电商，或关键流程无法在平台规则内表达时。",
    { label: "Shopify 开发者文档", url: "https://shopify.dev/docs" },
  ),
  tech(
    "supabase",
    "Supabase",
    "后端服务",
    "advanced",
    "围绕 PostgreSQL 提供数据库、认证、存储、实时与函数等托管能力的平台。",
    ["适合快速构建有数据的应用", "SQL/PostgreSQL 基础可迁移", "常用能力集成度高"],
    ["行级安全和权限配置需要专业判断", "托管方便不等于无需备份、监控和成本治理"],
    "小团队构建登录、数据和上传型应用，并能维护数据库权限时。",
    "仅静态网站，或团队无法承担身份、权限和数据安全责任时。",
    { label: "Supabase 官方文档", url: "https://supabase.com/docs" },
  ),
  tech(
    "postgresql",
    "PostgreSQL",
    "数据库",
    "advanced",
    "开源关系型数据库系统，支持 SQL、事务、约束和扩展。",
    ["数据一致性能力强", "生态成熟", "适合结构化业务数据"],
    ["需要建模、迁移、备份和性能维护", "不能把权限问题只交给前端"],
    "订单、用户、内容关系或关键业务规则需要可靠约束时。",
    "只存少量静态内容，数据库会增加无收益运维时。",
    { label: "PostgreSQL 官方文档", url: "https://www.postgresql.org/docs/" },
    "stable",
  ),
  tech(
    "vercel",
    "Vercel",
    "托管与部署",
    "core",
    "面向 Web 应用的托管与部署平台，尤其与 Next.js 生态结合紧密。",
    ["预览部署与 Git 工作流顺畅", "全球分发和常见前端能力集成", "适合快速迭代"],
    ["价格、限制和运行时能力会变化", "地区访问与供应商锁定需实测"],
    "使用 Next.js/前端框架并重视预览和部署体验时。",
    "必须完全自托管，或目标地区/合规条件未经验证时。",
    { label: "Vercel 官方文档", url: "https://vercel.com/docs" },
  ),
  tech(
    "cloudflare",
    "Cloudflare Pages / Workers",
    "托管与部署",
    "advanced",
    "Cloudflare 的静态站托管与边缘运行平台组合。",
    ["全球网络与缓存能力强", "静态到边缘函数可逐步扩展", "适合 PWA 和 API 边缘场景"],
    ["运行时与传统 Node 服务器存在差异", "配额、地区与数据服务需按官方文档核验"],
    "静态站、边缘函数或全球分发需求明确时。",
    "依赖不兼容边缘运行时的服务器库，且不愿适配时。",
    { label: "Cloudflare 开发者文档", url: "https://developers.cloudflare.com/" },
  ),
  tech(
    "netlify",
    "Netlify",
    "托管与部署",
    "core",
    "提供站点构建、部署、边缘网络与 Web 平台能力的托管服务。",
    ["Git 驱动部署成熟", "静态网站上手快", "预览与表单等常见功能集成"],
    ["套餐与能力会变化", "高级后端和地区需求需单独评估"],
    "静态或前端框架网站，需要托管式构建和预览时。",
    "核心系统要求完全自控基础设施或特定地区服务时。",
    { label: "Netlify 官方文档", url: "https://docs.netlify.com/" },
  ),
  tech(
    "github-pages",
    "GitHub Pages",
    "托管与部署",
    "core",
    "从 GitHub 仓库发布静态网站的托管服务。",
    ["与仓库集成直接", "适合文档、作品集和演示", "静态内容维护简单"],
    ["不提供通用服务器后端", "复杂重写、隐私或业务可用性要求需另选平台"],
    "公开静态项目、文档和低风险网站。",
    "需要服务器密钥、登录、交易或严格商业 SLA 时。",
    { label: "GitHub Pages 文档", url: "https://docs.github.com/pages" },
  ),
  tech(
    "playwright",
    "Playwright",
    "测试与质量",
    "core",
    "用于自动化 Chromium、Firefox 和 WebKit 的端到端测试与浏览器自动化框架。",
    ["能验证真实用户路径", "支持多浏览器和设备配置", "适合回归关键流程"],
    ["测试环境和数据需要维护", "不稳定选择器会产生脆弱测试", "不能替代人工 UAT"],
    "有关键交互、表单、登录或多页面路径时。",
    "纯静态一页且维护测试的成本明显超过风险时，可采用更轻的浏览器检查。",
    { label: "Playwright 官方文档", url: "https://playwright.dev/docs/intro" },
  ),
  tech(
    "lighthouse",
    "Lighthouse",
    "测试与质量",
    "core",
    "对网页性能、可访问性、最佳实践和 SEO 运行自动化审计的工具。",
    ["快速发现常见问题", "可在 CI 中重复", "报告便于定位改进方向"],
    ["分数受环境影响", "自动审计不能证明完整可访问性或真实业务体验"],
    "作为性能与基础质量的诊断信号。",
    "把单次满分当成上线保证或唯一 KPI 时。",
    { label: "Chrome Developers · Lighthouse", url: "https://developer.chrome.com/docs/lighthouse/" },
  ),
  tech(
    "sentry",
    "Sentry",
    "监控与运维",
    "advanced",
    "面向应用错误、性能和可观测性的托管产品。",
    ["能发现真实用户遇到的错误", "支持版本和发布关联", "有助于上线后闭环"],
    ["需要正确脱敏和采样", "第三方脚本、成本与地区合规需评估", "监控不能替代修复责任"],
    "动态应用或关键表单需要上线后错误追踪时。",
    "无法合法收集所需遥测，或只需简单可用性检查时。",
    { label: "Sentry 官方文档", url: "https://docs.sentry.io/" },
  ),
  tech(
    "github-actions",
    "GitHub Actions",
    "工程自动化",
    "advanced",
    "由仓库事件触发的自动化工作流平台。",
    ["可自动运行构建、测试和扫描", "与 PR 状态结合", "适合把 SOP 变成门禁"],
    ["第三方 Action 需要供应链审查", "秘密和权限配置错误会扩大风险", "运行费用与限制会变化"],
    "仓库托管在 GitHub，需要一致的质量门和定期任务时。",
    "工作流要接触高权限生产资源，却没有最小权限和审批时。",
    { label: "GitHub Actions 文档", url: "https://docs.github.com/actions" },
  ),
  tech(
    "codex",
    "Codex",
    "AI 编程",
    "core",
    "OpenAI 的编码代理产品，可在提供的项目上下文和工具权限范围内读、改、运行与验证代码。",
    ["能跨文件实施并运行反馈", "适合按 Spec 和垂直切片工作", "可使用项目级规则和 Skills"],
    ["不能替代业务签字和架构责任", "权限、上下文或验收模糊时会放大错误", "产品能力会更新"],
    "任务边界、资料来源和验证方式清楚，并有人审查结果时。",
    "把含密钥和个人信息的内容无边界交给代理，或期待一句提示完成高风险生产系统时。",
    { label: "OpenAI · Codex 文档", url: "https://developers.openai.com/codex/" },
  ),
];

const glossary = (
  id: string,
  term: string,
  category: string,
  level: GlossaryRecord["level"],
  definition: string,
  whyItMatters: string,
  source: GlossaryRecord["source"],
  claimType: GlossaryRecord["claimType"] = "fact",
  aliases?: string[],
  volatility: GlossaryRecord["volatility"] = "stable",
): GlossaryRecord => ({
  id,
  term,
  aliases,
  level,
  category,
  definition,
  whyItMatters,
  source,
  reviewedAt: REVIEW_DATE,
  volatility,
  claimType,
});

const mdn = (path: string, label = "MDN Web Docs") => ({
  label,
  url: `https://developer.mozilla.org/docs/${path}`,
});
const githubDocs = (path: string) => ({ label: "GitHub Docs", url: `https://docs.github.com/${path}` });

export const GLOSSARY: GlossaryRecord[] = [
  glossary("spec", "Spec", "需求与设计", "core", "Specification 的简称，是对目标、范围、约束、行为和验收的书面约定。它不等于一份固定模板。", "让人和 AI 在动手前对“做什么、怎样算完成”达成同一理解。", { label: "ISO/IEC/IEEE 29148 概览", url: "https://www.iso.org/standard/72089.html" }),
  glossary("sdd", "SDD（本文：Spec-Driven Development）", "AI 工程", "core", "本文把 SDD 用作 Spec-Driven Development：先形成可验证规范，再计划、实现和验收。其他资料中 SDD 也可能指 Software Design Description 等不同概念。", "避免把一个缩写误当成全行业唯一标准；使用时应先声明定义。", { label: "Addy Osmani · spec-driven-development Skill", url: "https://github.com/addyosmani/agent-skills/tree/main/skills/spec-driven-development" }, "engineering-judgment", ["Spec-Driven Development"], "changing"),
  glossary("vibe-coding", "Vibe Coding", "AI 工程", "core", "行业俗称，通常指主要通过自然语言和 AI 生成代码、较少逐行手写或理解实现细节的工作方式；不是正式工程标准。", "它可以加速探索，但是否能上线取决于规范、架构、测试、安全和责任，而不是名称本身。", { label: "Merriam-Webster · vibe coding", url: "https://www.merriam-webster.com/slang/vibe-coding" }, "informal", undefined, "changing"),
  glossary("prd", "PRD", "需求与设计", "core", "Product Requirements Document，记录产品目标、用户、范围、需求和成功标准的文档。团队对 PRD 的格式并无单一标准。", "把商业与用户需求保留下来，避免只剩实现细节。", { label: "Atlassian · Product requirements", url: "https://www.atlassian.com/agile/product-management/requirements" }, "engineering-judgment", ["产品需求文档"]),
  glossary("adr", "ADR", "架构", "core", "Architecture Decision Record，记录一个重要架构决定、背景、选项、结果与后果。", "让未来的人和 AI 知道“为什么这样选”，避免反复推翻旧决策。", { label: "ADR GitHub 组织", url: "https://adr.github.io/" }, "fact", ["架构决策记录"]),
  glossary("sitemap", "Sitemap", "内容与信息架构", "core", "可指面向规划的信息架构页面树，也可指供搜索引擎读取的 XML URL 清单；语境不同含义不同。", "前者帮助设计导航，后者帮助搜索引擎发现 URL，不能混用。", { label: "Google Search Central · Sitemaps", url: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview" }),
  glossary("wireframe", "Wireframe", "需求与设计", "core", "用低保真结构表达页面区域、层级和交互的线框图。", "先验证布局和流程，避免过早争论颜色和装饰。", { label: "Nielsen Norman Group · Wireflows", url: "https://www.nngroup.com/articles/wireflows/" }, "engineering-judgment", ["线框图"]),
  glossary("prototype", "Prototype", "需求与设计", "core", "为验证问题而制作的可交互或可观察模型，可能被明确丢弃。", "原型用于学习，不应未经评审直接演化成生产系统。", { label: "Interaction Design Foundation · Prototypes", url: "https://www.interaction-design.org/literature/topics/prototyping" }, "engineering-judgment", ["原型"]),
  glossary("design-system", "Design System", "需求与设计", "advanced", "由设计原则、令牌、组件、模式和文档组成的可复用体系。", "让多个页面与多人协作保持一致，并把设计判断转成约束。", { label: "W3C Design System", url: "https://design-system.w3.org/" }, "engineering-judgment", ["设计系统"]),
  glossary("component", "Component", "前端", "core", "具有明确输入、状态和输出的可复用界面单元。", "合适的组件边界能减少重复；过度组件化会增加跳转和抽象。", { label: "React · Your First Component", url: "https://react.dev/learn/your-first-component" }, "engineering-judgment", ["组件"]),
  glossary("responsive", "Responsive Web Design", "前端", "core", "让布局和内容适应不同屏幕、输入方式和用户设置的设计方法。", "移动端不是桌面缩小版；需要验证重排、触控和内容优先级。", mdn("Learn/CSS/CSS_layout/Responsive_Design"), "fact", ["响应式设计"]),
  glossary("semantic-html", "Semantic HTML", "前端", "core", "根据内容和控件含义选择 HTML 元素，而不是只按外观选择。", "有助于阅读顺序、键盘操作、搜索理解和辅助技术。", mdn("Glossary/Semantics"), "fact", ["语义化 HTML"]),
  glossary("accessibility", "Accessibility", "质量", "core", "让残障用户及处在不同环境中的人可以感知、操作、理解和可靠使用产品。", "它涉及结构、键盘、对比度、标签、错误恢复等，不是最后跑一次分数。", { label: "W3C · Introduction to Web Accessibility", url: "https://www.w3.org/WAI/fundamentals/accessibility-intro/" }, "fact", ["A11y", "无障碍"]),
  glossary("wcag", "WCAG", "质量", "advanced", "Web Content Accessibility Guidelines，由 W3C WAI 发布的可访问性指南。", "可作为验收依据，但自动工具和截图都不能单独证明完整符合。", { label: "W3C · WCAG", url: "https://www.w3.org/WAI/standards-guidelines/wcag/" }),
  glossary("seo", "SEO", "内容与增长", "core", "Search Engine Optimization，通过可抓取内容、技术质量和有用信息改善搜索引擎理解与展示。", "应服务真实用户和可验证内容，不等于堆关键词。", { label: "Google Search Essentials", url: "https://developers.google.com/search/docs/essentials" }, "fact", ["搜索引擎优化"], "changing"),
  glossary("geo", "GEO（生成式引擎优化）", "内容与增长", "advanced", "围绕生成式搜索或回答系统可发现、可引用内容的一组新兴实践；目前不是统一、稳定的正式标准。", "可以强化来源、结构和实体一致性，但不应承诺被 AI 引用或用它替代基本 SEO。", { label: "Princeton · GEO 论文", url: "https://arxiv.org/abs/2311.09735" }, "informal", ["Generative Engine Optimization"], "changing"),
  glossary("domain", "Domain Name", "发布与网络", "core", "人类可读的网站名称，经 DNS 解析到网络服务。", "域名所有权、续费和 DNS 权限必须明确由谁管理。", { label: "ICANN · Domain Name Registration", url: "https://www.icann.org/resources/pages/domain-name-registration-process-2020-06-22-en" }, "fact", ["域名"]),
  glossary("dns", "DNS", "发布与网络", "core", "Domain Name System，把域名映射到 IP 地址或其他记录的分布式系统。", "切换网站、邮件验证和 HTTPS 都常依赖 DNS，错误会影响整个域名。", { label: "Cloudflare Learning · DNS", url: "https://www.cloudflare.com/learning/dns/what-is-dns/" }),
  glossary("hosting", "Hosting", "发布与网络", "core", "让网站文件或应用运行并可被网络访问的服务。", "托管选择会影响运行时、地区、成本、可恢复性和运维责任。", mdn("Learn/Common_questions/Web_mechanics/What_is_a_web_server"), "fact", ["网站托管"]),
  glossary("cdn", "CDN", "发布与网络", "core", "Content Delivery Network，通过分布式节点缓存和传递内容。", "可以降低部分地区延迟和源站压力，但不能自动解决所有动态请求与合规问题。", { label: "Cloudflare Learning · CDN", url: "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/" }),
  glossary("https", "HTTPS / TLS", "发布与网络", "core", "HTTPS 是在 TLS 保护下传输 HTTP 的方式，用于加密并验证连接。", "正式网站应启用 HTTPS；它保护传输，不等于网站本身没有漏洞。", mdn("Glossary/HTTPS"), "fact", ["TLS"]),
  glossary("pwa", "PWA", "前端", "advanced", "Progressive Web App，使用 Web 平台能力提供可安装、离线等渐进增强体验的应用方式。", "离线和安装能力需按需要设计；PWA 不是单一框架，也不会自动跨平台一致。", mdn("Web/Progressive_web_apps"), "fact", ["渐进式 Web 应用"], "changing"),
  glossary("service-worker", "Service Worker", "前端", "advanced", "浏览器在页面之外运行的脚本，可拦截请求、管理缓存和支持离线等能力。通常要求 HTTPS 或 localhost。", "单独以 file:// 打开 HTML 时不能依赖它，因此离线单 HTML必须把核心资源内联。", mdn("Web/API/Service_Worker_API"), "fact", ["服务工作线程"]),
  glossary("api", "API", "架构", "core", "Application Programming Interface，是系统或模块对外暴露的交互契约。", "API 需要定义输入、输出、错误、权限和版本，而不只是一个网址。", mdn("Glossary/API")),
  glossary("rest", "REST", "架构", "advanced", "一种面向资源、使用统一接口等约束的架构风格；很多被称为 REST API 的接口只采用其中部分思想。", "不要为了名称强行套格式，应优先保证清晰契约和错误语义。", { label: "Roy Fielding Dissertation", url: "https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm" }, "fact", ["REST API"]),
  glossary("authn", "Authentication", "安全", "core", "确认一个主体是谁的过程。", "登录只是认证入口；会话、密码、多因素和恢复都属于认证设计。", { label: "OWASP · Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" }, "fact", ["AuthN", "身份认证"]),
  glossary("authz", "Authorization", "安全", "core", "决定已识别主体可以访问什么资源或执行什么操作。", "有登录不等于有正确权限；每次敏感操作都应在可信边界校验。", { label: "OWASP · Authorization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html" }, "fact", ["AuthZ", "授权"]),
  glossary("session", "Session", "安全", "advanced", "服务器或系统在一段时间内关联用户交互状态的机制。", "会话标识需要安全存储、过期、撤销并防止固定或劫持。", { label: "OWASP · Session Management", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" }, "fact", ["会话"]),
  glossary("cookie", "Cookie", "Web 基础", "core", "网站让浏览器随相关请求保存并发送的小段数据。", "可用于会话和偏好；应正确设置 Secure、HttpOnly、SameSite 等属性并遵守隐私要求。", mdn("Web/HTTP/Guides/Cookies")),
  glossary("local-storage", "localStorage", "Web 基础", "core", "浏览器按来源持久保存字符串键值的同步 Web Storage API。", "适合本机非敏感草稿与偏好，不应用来保存密码、服务器密钥或可信权限。", mdn("Web/API/Window/localStorage"), "fact", ["本地存储"]),
  glossary("database", "Database", "数据", "core", "按一定模型组织、读取和更新数据的系统。", "是否需要数据库取决于数据和业务规则，不应因使用 AI 就默认添加。", { label: "PostgreSQL · What is PostgreSQL", url: "https://www.postgresql.org/about/" }, "engineering-judgment", ["数据库"]),
  glossary("schema", "Schema", "数据", "core", "描述数据结构、类型、关系和约束的定义。", "明确 Schema 能让表单、API、数据库与 AI 对同一数据形状达成一致。", { label: "PostgreSQL · DDL", url: "https://www.postgresql.org/docs/current/ddl.html" }, "fact", ["数据模式"]),
  glossary("migration", "Database Migration", "数据", "advanced", "对数据库结构或数据进行受控版本变更的过程。", "生产迁移需要备份、兼容窗口、验证和回滚，不能只在本地“跑通”。", { label: "Prisma · Database migrations", url: "https://www.prisma.io/docs/orm/prisma-migrate/understanding-prisma-migrate/overview" }, "engineering-judgment", ["数据库迁移"], "changing"),
  glossary("ci-cd", "CI / CD", "工程化", "core", "CI 持续集成用于频繁合并并自动验证；CD 可指持续交付或持续部署，团队需说明具体含义。", "把构建、测试、扫描和发布步骤变成可重复门禁。", githubDocs("actions/about-github-actions/understanding-github-actions"), "fact", ["持续集成", "持续交付"]),
  glossary("lint", "Lint", "工程化", "core", "用静态规则检查代码中的错误模式和风格问题。", "适合快速反馈，但规则通过不等于功能、安全和体验正确。", { label: "ESLint 官方文档", url: "https://eslint.org/docs/latest/use/core-concepts" }),
  glossary("type-check", "Type Checking", "工程化", "core", "检查程序中值与声明类型是否一致的过程。", "能提前发现大量接口错误，但无法证明运行时数据和业务规则正确。", { label: "TypeScript · Everyday Types", url: "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html" }, "fact", ["类型检查"]),
  glossary("unit-test", "Unit Test", "测试", "core", "在较小边界内验证一个函数、模块或组件行为的自动测试。", "反馈快，适合业务规则；如果过度依赖内部实现会阻碍重构。", { label: "Martin Fowler · Unit Test", url: "https://martinfowler.com/bliki/UnitTest.html" }, "engineering-judgment", ["单元测试"]),
  glossary("integration-test", "Integration Test", "测试", "advanced", "验证多个模块、服务或基础设施之间协作的测试。", "能发现契约与配置问题，但通常比单元测试更慢、更依赖环境。", { label: "Martin Fowler · Integration Test", url: "https://martinfowler.com/bliki/IntegrationTest.html" }, "engineering-judgment", ["集成测试"]),
  glossary("e2e", "End-to-End Test", "测试", "core", "从用户入口跨越主要系统边界验证完整路径的测试。", "适合保护关键流程，但数量过多会变慢且维护成本高。", { label: "Playwright · Best Practices", url: "https://playwright.dev/docs/best-practices" }, "engineering-judgment", ["E2E", "端到端测试"]),
  glossary("uat", "UAT", "测试", "core", "User Acceptance Testing，由业务或代表性用户依据约定确认系统是否满足实际需要。", "开发者和 AI 不能代替业务负责人确认内容、流程和合规。", { label: "ISTQB Glossary", url: "https://glossary.istqb.org/en_US/term/acceptance-testing" }, "fact", ["用户验收测试"]),
  glossary("vertical-slice", "Vertical Slice", "工程化", "core", "沿一个用户结果贯穿所需界面、逻辑和数据边界的最小完整改动。", "能快速获得真实反馈，避免先铺满数据库、再铺满接口、最后才看到页面。", { label: "Jimmy Bogard · Vertical Slice Architecture", url: "https://www.jimmybogard.com/vertical-slice-architecture/" }, "engineering-judgment", ["垂直切片"]),
  glossary("mvp", "MVP", "需求与设计", "core", "Minimum Viable Product，用最小可行产品验证关键价值假设；不等于质量可以随意降低。", "帮助缩小范围，但安全、隐私和基本可用性不能被当成可选。", { label: "Eric Ries · Minimum Viable Product", url: "https://leanstartup.co/resources/articles/minimum-viable-product-mvp/" }, "engineering-judgment", ["最小可行产品"]),
  glossary("rollback", "Rollback", "发布与运维", "core", "在发布失败或风险超阈值时恢复到已知可用状态的过程。", "需要事先定义触发条件、版本、数据兼容和负责人。", { label: "Google SRE · Release Engineering", url: "https://sre.google/sre-book/release-engineering/" }, "engineering-judgment", ["回滚"]),
  glossary("observability", "Observability", "发布与运维", "advanced", "通过系统输出推断内部状态的能力，常结合日志、指标和追踪。", "让团队能回答线上发生了什么，而不只是“服务还在”。", { label: "OpenTelemetry · Observability primer", url: "https://opentelemetry.io/docs/concepts/observability-primer/" }, "fact", ["可观测性"]),
  glossary("monitoring", "Monitoring", "发布与运维", "core", "持续收集和评估已知信号，并在达到条件时展示或告警。", "静态网站也要监控可访问性、证书和表单；动态系统还需错误与延迟。", { label: "Google SRE · Monitoring", url: "https://sre.google/sre-book/monitoring-distributed-systems/" }, "engineering-judgment", ["监控"]),
  glossary("slo", "SLO / SLA", "发布与运维", "advanced", "SLO 是服务可靠性目标；SLA 是与用户或客户之间可能带有后果的服务承诺。", "先有可测 SLI 和责任，再谈承诺；小网站不必机械套企业级指标。", { label: "Google SRE · Service Level Objectives", url: "https://sre.google/sre-book/service-level-objectives/" }, "fact", ["SLA", "服务等级目标"]),
  glossary("rpo-rto", "RPO / RTO", "发布与运维", "advanced", "RPO 表示可接受的数据丢失时间范围；RTO 表示灾难后恢复服务的目标时间。", "决定备份频率、恢复方案和演练标准。", { label: "AWS · Disaster recovery", url: "https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-dr-objectives.html" }, "fact", ["恢复点目标", "恢复时间目标"]),
  glossary("feature-flag", "Feature Flag", "发布与运维", "advanced", "在不重新部署全部代码的情况下控制功能是否对特定用户或环境开放的机制。", "支持灰度和快速关闭，但长期不清理会形成分支复杂度。", { label: "Martin Fowler · Feature Toggles", url: "https://martinfowler.com/articles/feature-toggles.html" }, "engineering-judgment", ["功能开关"]),
  glossary("csp", "CSP", "安全", "advanced", "Content Security Policy，通过响应头限制页面可加载或执行的资源。", "可降低部分 XSS 影响，但策略需要与真实资源清单一致。", mdn("Web/HTTP/Guides/CSP"), "fact", ["内容安全策略"]),
  glossary("cors", "CORS", "安全", "advanced", "Cross-Origin Resource Sharing，让服务器通过 HTTP 头声明哪些跨来源浏览器请求可被读取。", "CORS 不是身份认证，也不阻止服务器到服务器请求。", mdn("Web/HTTP/Guides/CORS"), "fact", ["跨来源资源共享"]),
  glossary("secret", "Secret", "安全", "core", "密码、私钥、令牌等一旦泄露就可能授予敏感访问的值。", "不能放进前端代码、公开仓库、提示词示例或项目 JSON。", { label: "GitHub · Secret scanning", url: "https://docs.github.com/code-security/secret-scanning/introduction/about-secret-scanning" }, "engineering-judgment", ["密钥"]),
  glossary("environment-variable", "Environment Variable", "工程化", "core", "由运行环境提供给进程的名称和值，常用于配置。", "它是配置传递机制，不自动等于安全保管；前端构建变量可能公开。", { label: "Node.js · Environment Variables", url: "https://nodejs.org/api/environment_variables.html" }, "fact", ["环境变量"]),
  glossary("dependency", "Dependency", "工程化", "core", "项目运行或开发依赖的外部包、服务或系统。", "每个依赖都带来更新、许可证、供应链和迁移责任。", { label: "npm Docs · Dependencies", url: "https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file" }, "engineering-judgment", ["依赖"]),
  glossary("package-manager", "Package Manager", "工程化", "core", "解析、安装和记录软件依赖的工具，如 npm、pnpm 或 yarn。", "应保留锁文件并在项目中统一使用，避免环境差异。", { label: "npm Docs", url: "https://docs.npmjs.com/" }, "fact", ["包管理器"]),
  glossary("ssr-ssg-csr", "SSR / SSG / CSR", "前端", "advanced", "SSR 在请求时由服务器生成 HTML；SSG 在构建时生成；CSR 主要在浏览器运行后生成界面。现代框架可混合使用。", "选择应按内容更新、缓存、交互和运行成本，而不是把一种模式用于所有页面。", { label: "Next.js · Rendering", url: "https://nextjs.org/docs/app/getting-started/server-and-client-components" }, "fact", ["服务端渲染", "静态生成", "客户端渲染"], "changing"),
  glossary("headless-cms", "Headless CMS", "内容与信息架构", "advanced", "把内容管理后台与前端展示分离，并通过 API 提供内容的 CMS。", "适合多渠道和运营编辑，但会增加内容模型、预览、权限和 API 依赖。", { label: "Contentful · Headless CMS", url: "https://www.contentful.com/headless-cms/" }, "engineering-judgment", ["无头 CMS"], "changing"),
  glossary("webhook", "Webhook", "架构", "advanced", "当事件发生时，一个系统向另一个系统发送 HTTP 请求的集成方式。", "需要签名验证、重试、幂等和失败队列，不能信任来路不明的请求。", { label: "GitHub · Webhooks", url: "https://docs.github.com/webhooks/about-webhooks" }, "fact", ["事件回调"]),
  glossary("rate-limit", "Rate Limiting", "安全", "advanced", "限制单位时间内请求或操作次数的机制。", "可降低滥用和资源耗尽风险，但要设计用户提示、重试和分布式一致性。", { label: "OWASP · Denial of Service", url: "https://cheatsheetseries.owasp.org/cheatsheets/Denial_of_Service_Cheat_Sheet.html" }, "engineering-judgment", ["限流"]),
  glossary("idempotency", "Idempotency", "架构", "advanced", "同一操作重复执行一次或多次，对系统产生相同最终效果的性质。", "支付、订单和 webhook 重试尤其需要幂等，避免重复扣款或重复创建。", { label: "IETF HTTP Semantics · Idempotent Methods", url: "https://www.rfc-editor.org/rfc/rfc9110.html#name-idempotent-methods" }, "fact", ["幂等"]),
  glossary("core-web-vitals", "Core Web Vitals", "质量", "core", "Google 定义的一组面向真实用户体验的加载、交互响应和视觉稳定指标。具体阈值与指标可能更新。", "应结合真实用户和业务场景测量，不把单次实验室分数当结论。", { label: "web.dev · Core Web Vitals", url: "https://web.dev/articles/vitals" }, "fact", ["核心 Web 指标"], "changing"),
  glossary("performance-budget", "Performance Budget", "质量", "advanced", "为资源大小、请求数或用户体验指标设定可检查上限。", "把“网站要快”转成在 CI 和评审中可执行的边界。", { label: "web.dev · Performance budgets", url: "https://web.dev/articles/performance-budgets-101" }, "engineering-judgment", ["性能预算"]),
];
