import type {
  ContentOwnerId,
  FeatureId,
  PriorityId,
  PromptTemplate,
  RegionId,
  StageDefinition,
  StartPointId,
  WebsiteTypeId,
} from "./types";

export const REVIEW_DATE = "2026-07-20";

export const WEBSITE_TYPES: Array<{
  id: WebsiteTypeId;
  label: string;
  description: string;
}> = [
  { id: "corporate", label: "企业官网", description: "介绍业务、能力、案例并获取询盘。" },
  { id: "landing", label: "落地页", description: "围绕一个活动、产品或转化目标。" },
  { id: "portfolio", label: "作品集", description: "展示个人或团队作品与服务。" },
  { id: "blog", label: "博客 / 文档", description: "持续发布文章、教程或产品文档。" },
  { id: "app", label: "Web App / SaaS", description: "用户登录后完成持续性的线上任务。" },
  { id: "ecommerce", label: "电商", description: "商品、库存、订单、支付与售后。" },
  { id: "internal", label: "内部工具", description: "面向团队的审批、数据或运营工具。" },
];

export const START_POINTS: Array<{
  id: StartPointId;
  label: string;
  description: string;
  inferredStage: number;
}> = [
  { id: "idea", label: "只有想法", description: "还没有成体系的资料。", inferredStage: 1 },
  { id: "materials", label: "已有资料", description: "有文案、图片、业务资料或调研。", inferredStage: 2 },
  { id: "design", label: "已有设计", description: "有线框图、原型或视觉稿。", inferredStage: 4 },
  { id: "code", label: "已有代码", description: "项目已经开始开发。", inferredStage: 5 },
  { id: "live", label: "已有线上网站", description: "需要改造、接手或继续运营。", inferredStage: 8 },
];

export const FEATURES: Array<{
  id: FeatureId;
  label: string;
  description: string;
}> = [
  { id: "login", label: "登录", description: "需要识别不同用户。" },
  { id: "permissions", label: "权限", description: "不同角色能看到或操作不同内容。" },
  { id: "personal-data", label: "个人信息", description: "会收集姓名、电话、邮箱等信息。" },
  { id: "upload", label: "文件上传", description: "用户可上传图片、文档或其他文件。" },
  { id: "payment", label: "支付 / 交易", description: "涉及付款、退款、订单或对账。" },
];

export const CONTENT_OWNERS: Array<{ id: ContentOwnerId; label: string; description: string }> = [
  { id: "self-ai", label: "本人 / AI", description: "内容不频繁变化，可通过代码或文件更新。" },
  { id: "developer", label: "开发者", description: "由懂代码的人维护和发布。" },
  { id: "operator", label: "运营人员", description: "需要可视化后台或 CMS。" },
  { id: "approval", label: "多人审批", description: "需要草稿、审核、发布和权限记录。" },
];

export const REGIONS: Array<{ id: RegionId; label: string; description: string }> = [
  { id: "mainland", label: "中国大陆", description: "需要额外评估备案、网络、云服务和数据要求。" },
  { id: "global", label: "全球", description: "优先全球 CDN、国际服务兼容与多语言。" },
  { id: "both", label: "两者兼顾", description: "需要分别验证线路、合规和第三方服务可用性。" },
];

export const PRIORITIES: Array<{ id: PriorityId; label: string; description: string }> = [
  { id: "speed", label: "最快上线", description: "优先成熟托管服务和更少自定义。" },
  { id: "cost", label: "成本", description: "优先静态方案和可预测费用。" },
  { id: "ownership", label: "代码所有权", description: "优先可导出、可迁移和标准技术。" },
  { id: "visual-editing", label: "可视化编辑", description: "优先非开发者可维护的 CMS 或建站工具。" },
  { id: "scale", label: "复杂业务扩展", description: "优先清晰边界、测试和可扩展基础设施。" },
];

export const STAGE_STATUS_LABELS = {
  not_started: "未开始",
  in_progress: "进行中",
  blocked: "被阻塞",
  review: "待验收 / 待复核",
  done: "已完成",
  not_applicable: "不适用",
} as const;

export const STAGES: StageDefinition[] = [
  {
    id: 1,
    title: "明确目标与网站类型",
    plainGoal: "先说明网站为谁解决什么问题，以及怎样才算成功。",
    deliverables: ["项目简报", "目标用户描述", "成功指标与边界"],
    promptIds: ["project-kickoff"],
    gates: [
      {
        id: "goal",
        title: "目标和非目标已写清",
        help: "至少写出一个业务目标，以及本期明确不做的内容。",
        evidenceExample: "项目简报链接，或一段已确认的目标/非目标说明。",
      },
      {
        id: "audience",
        title: "主要用户和首要任务已确认",
        help: "不能只写“所有人”；需要一个主要用户及其访问目的。",
        evidenceExample: "用户画像、访谈记录或业务负责人的确认。",
      },
      {
        id: "success",
        title: "成功标准可以被观察",
        help: "例如能提交有效询盘、完成购买、找到文档答案，而不是“看起来高级”。",
        evidenceExample: "1—3 项可检查的业务或用户结果。",
      },
    ],
  },
  {
    id: 2,
    title: "收集用户、业务和内容资料",
    plainGoal: "把可核验的事实、内容和来源准备好，避免 AI 猜测。",
    deliverables: ["来源清单", "内容盘点表", "缺口与责任人"],
    promptIds: ["source-research", "content-inventory"],
    gates: [
      {
        id: "sources",
        title: "关键事实有来源",
        help: "公司、产品、价格、政策、能力和案例不能只靠 AI 生成。",
        evidenceExample: "资料清单，含来源、日期、负责人和可公开范围。",
      },
      {
        id: "content-inventory",
        title: "页面所需内容已盘点",
        help: "列出已有、缺失、需改写和禁止公开的文案/图片/数据。",
        evidenceExample: "内容表格或逐页素材清单。",
      },
      {
        id: "content-owner",
        title: "内容维护责任已确定",
        help: "明确上线后谁更新、谁审核、多久检查一次。",
        evidenceExample: "责任人和审核流程说明。",
      },
      {
        id: "data-inventory",
        title: "个人信息和敏感数据已盘点",
        help: "记录收集什么、为什么收集、保存多久以及谁能访问。",
        evidenceExample: "数据清单或隐私评审记录。",
        requiresAnyFeature: ["personal-data", "upload", "payment"],
      },
    ],
  },
  {
    id: 3,
    title: "编写 Spec、页面结构与内容清单",
    plainGoal: "把聊天中的想法变成有范围、有验收、可交接的书面约定。",
    deliverables: ["Spec / PRD", "Sitemap", "逐页内容与验收清单"],
    promptIds: ["spec-prd", "sitemap-content"],
    gates: [
      {
        id: "spec",
        title: "Spec 包含范围、非范围和约束",
        help: "至少说明目标、用户、功能、内容、技术/业务约束和未知项。",
        evidenceExample: "已评审的 Spec 或 PRD。",
      },
      {
        id: "sitemap",
        title: "页面结构与用户路径已确认",
        help: "每一页都要服务一个用户任务，不为凑页面而存在。",
        evidenceExample: "Sitemap、主导航和关键路径。",
      },
      {
        id: "acceptance",
        title: "关键结果有可测试验收条件",
        help: "写成用户能看到的结果，并包含错误、空状态和移动端。",
        evidenceExample: "Given/When/Then 或清晰的验收清单。",
      },
      {
        id: "commerce-rules",
        title: "交易规则和异常流程已确认",
        help: "覆盖价格、库存、支付失败、退款、订单状态和售后责任。",
        evidenceExample: "订单状态图或交易业务规则。",
        appliesTo: ["ecommerce"],
      },
    ],
  },
  {
    id: 4,
    title: "选择技术方案并验证设计",
    plainGoal: "用需求选择工具，并先验证最重要的页面和交互。",
    deliverables: ["技术决策记录（ADR）", "原型或视觉稿", "风险与约束清单"],
    promptIds: ["stack-adr", "design-review"],
    gates: [
      {
        id: "adr",
        title: "首选、简化和扩展方案已比较",
        help: "说明为什么选、什么时候不适用，以及迁移或锁定风险。",
        evidenceExample: "ADR 或技术方案对比。",
      },
      {
        id: "prototype",
        title: "关键页面或流程已用真实内容验证",
        help: "原型需要覆盖首屏、主要行动和关键错误/空状态。",
        evidenceExample: "可打开的原型、截图或评审记录。",
      },
      {
        id: "mainland-constraint",
        title: "中国大陆访问约束已单独验证",
        help: "这是附加约束，不应直接替代技术方案。需要检查备案、网络、第三方脚本和数据要求。",
        evidenceExample: "服务可用性、备案与合规核对记录。",
        regions: ["mainland", "both"],
      },
      {
        id: "threat-model",
        title: "高风险功能有最小威胁模型",
        help: "列出资产、入口、滥用方式、权限边界和失败后果。",
        evidenceExample: "威胁模型或安全设计评审。",
        requiresAnyFeature: ["login", "permissions", "personal-data", "upload", "payment"],
      },
    ],
  },
  {
    id: 5,
    title: "建立仓库、AI 上下文和质量基线",
    plainGoal: "先给 AI 边界、反馈和检查工具，再让它扩大改动。",
    deliverables: ["代码仓库", "项目上下文与 ADR", "自动检查基线"],
    promptIds: ["codex-implementation"],
    gates: [
      {
        id: "repository",
        title: "仓库可在干净环境安装和构建",
        help: "README 写明入口；锁文件、运行时和环境变量示例齐全。",
        evidenceExample: "干净环境构建记录或 CI 结果。",
      },
      {
        id: "ai-context",
        title: "AI 能读到目标、边界和工程约束",
        help: "至少包含项目说明、术语、目录边界、禁止事项和验收命令。",
        evidenceExample: "AGENTS.md、CONTEXT.md、Spec 和 ADR 链接。",
      },
      {
        id: "quality-baseline",
        title: "类型、Lint、测试和构建基线可重复",
        help: "不是所有项目都要同样多测试，但每个项目都要有快速反馈。",
        evidenceExample: "本地或 CI 的质量命令及通过记录。",
      },
      {
        id: "secrets",
        title: "密钥和环境配置没有进入公开代码",
        help: "使用环境变量示例、密钥扫描和最小权限；前端代码不保存服务器密钥。",
        evidenceExample: "秘密扫描结果和环境变量清单。",
        riskLevels: ["medium", "high"],
      },
    ],
  },
  {
    id: 6,
    title: "让 AI 按垂直切片开发",
    plainGoal: "一次完成一个用户可感知的小结果，并立刻验证。",
    deliverables: ["垂直切片任务", "实现与测试", "变更说明"],
    promptIds: ["vertical-slice", "codex-implementation"],
    gates: [
      {
        id: "thin-slice",
        title: "任务按用户结果切片",
        help: "一个切片应从界面到数据/内容完整可用，而不是同时铺开所有层。",
        evidenceExample: "单个任务的范围、非范围和验收。",
      },
      {
        id: "feedback-loop",
        title: "每个切片都有自动或可重复反馈",
        help: "至少包含构建、针对性测试或浏览器检查。",
        evidenceExample: "测试结果、截图或复现步骤。",
      },
      {
        id: "reviewed-change",
        title: "改动与 Spec、架构和安全边界一致",
        help: "评审既看代码质量，也看是否实现了正确需求。",
        evidenceExample: "代码评审记录或自审清单。",
      },
    ],
  },
  {
    id: 7,
    title: "测试、修复和业务验收",
    plainGoal: "证明网站在真实设备、真实内容和失败情况下仍然可用。",
    deliverables: ["测试报告", "无障碍与性能检查", "UAT 签字或结论"],
    promptIds: ["quality-review", "debug-review"],
    gates: [
      {
        id: "functional",
        title: "关键路径和失败路径已测试",
        help: "覆盖正常、空数据、无网络、输入错误和服务失败。",
        evidenceExample: "自动测试或人工测试记录。",
      },
      {
        id: "responsive-a11y",
        title: "移动端、键盘、缩放和语义已检查",
        help: "至少验证 390px、键盘操作、200% 缩放、清晰标签和可见焦点。",
        evidenceExample: "截图、键盘路径和无障碍检查结果。",
      },
      {
        id: "uat",
        title: "业务负责人按验收标准确认",
        help: "AI 或开发者不能代替内容、业务和合规负责人签字。",
        evidenceExample: "UAT 记录、未通过项和最终结论。",
      },
      {
        id: "security-test",
        title: "权限、输入、上传或支付经过针对性安全测试",
        help: "测试越权、滥用、错误数据、速率限制和敏感信息泄露。",
        evidenceExample: "安全测试记录和剩余风险。",
        riskLevels: ["high"],
      },
    ],
  },
  {
    id: 8,
    title: "发布、监控和持续改进",
    plainGoal: "让上线可观察、可回退、有人负责，而不是上传后结束。",
    deliverables: ["发布与回滚计划", "监控和责任人", "上线复盘"],
    promptIds: ["release-review"],
    gates: [
      {
        id: "release-plan",
        title: "发布步骤、负责人和时间窗已确认",
        help: "包括域名、环境变量、数据迁移、缓存、表单和第三方服务。",
        evidenceExample: "发布清单和批准记录。",
      },
      {
        id: "rollback",
        title: "回滚条件和恢复步骤已演练",
        help: "明确什么信号触发回滚、恢复到哪里、数据如何处理。",
        evidenceExample: "演练记录或可执行回滚说明。",
      },
      {
        id: "monitoring",
        title: "关键可用性和业务结果可被观察",
        help: "静态站至少检查可访问性与表单；动态系统还需错误、延迟和关键业务事件。",
        evidenceExample: "监控面板、告警规则或定期检查责任。",
      },
      {
        id: "privacy-release",
        title: "隐私、数据保留和用户权利已上线",
        help: "公开说明与真实数据处理一致，并验证删除/导出/撤回路径。",
        evidenceExample: "隐私声明、数据流程和验收记录。",
        requiresAnyFeature: ["personal-data", "upload", "payment"],
      },
    ],
  },
];

const commonProjectFields = [
  {
    id: "projectName",
    label: "项目名称",
    description: "可使用暂定名；不要填写客户隐私。",
    example: "松林咖啡官网（虚构示例）",
    required: true,
  },
  {
    id: "audience",
    label: "主要用户",
    description: "写一个最主要的人群和访问情境。",
    example: "正在寻找附近安静办公空间的自由职业者",
    required: true,
    multiline: true,
  },
  {
    id: "businessGoal",
    label: "业务目标",
    description: "写可观察的结果。",
    example: "让访客了解空间和价格，并预约到店参观",
    required: true,
    multiline: true,
  },
] satisfies PromptTemplate["fields"];

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: "project-kickoff",
    title: "项目启动与需求访谈",
    stageIds: [1],
    when: "只有一个想法，尚未形成可靠需求时。",
    preparation: ["你已知道的目标", "已有资料的位置", "能做决定的人"],
    deliverables: ["已确认事实", "未知项清单", "范围和非范围", "下一轮问题"],
    acceptance: ["事实、推测和建议分开", "每个关键未知项有责任人", "AI 未替业务方做决定"],
    stopConditions: ["缺少能确认目标的人", "目标之间存在未解决冲突"],
    fields: [
      ...commonProjectFields,
      {
        id: "knownMaterials",
        label: "已有资料",
        description: "写名称或来源，不要直接粘贴密码、客户名单。",
        example: "品牌说明、服务清单、旧网站链接、三份用户访谈",
        required: false,
        multiline: true,
        sensitiveWarning: true,
      },
    ],
    executionSteps: ["先复述已知事实", "一次只追问一个会改变路线的问题", "指出矛盾和缺口", "生成项目简报草案并等待确认"],
  },
  {
    id: "source-research",
    title: "有来源调研",
    stageIds: [2],
    when: "需要核对用户、竞品、行业、法规或技术事实时。",
    preparation: ["明确研究问题", "优先来源类型", "可接受的时间范围"],
    deliverables: ["结论摘要", "逐条来源", "证据强弱", "仍无法确认的内容"],
    acceptance: ["事实均可追溯到直接来源", "标出来源日期和适用范围", "不以搜索摘要代替原文"],
    stopConditions: ["只有二手转载且无法核验", "结论会改变高风险决策但证据不足"],
    fields: [
      {
        id: "researchQuestion",
        label: "研究问题",
        description: "一个具体、可回答的问题。",
        example: "目标用户选择共享办公空间时最关心哪些信息？",
        required: true,
        multiline: true,
      },
      {
        id: "trustedSources",
        label: "优先来源",
        description: "官方文档、法规原文、研究论文、用户访谈等。",
        example: "政府官网、产品官方文档、近两年的用户访谈",
        required: true,
        multiline: true,
      },
      {
        id: "dateScope",
        label: "时间与地域范围",
        description: "避免把过期或异地事实直接套用。",
        example: "2025 年至今，中国大陆与新加坡",
        required: false,
      },
    ],
    executionSteps: ["先列检索计划", "优先打开直接来源", "分别记录事实、合理推测和工程判断", "对矛盾来源给出解释，不强行统一"],
  },
  {
    id: "content-inventory",
    title: "内容资料盘点",
    stageIds: [2],
    when: "已有散落文案、图片、表格或旧网站，需要判断能否公开使用时。",
    preparation: ["资料目录", "公开范围", "内容负责人"],
    deliverables: ["已有/缺失/待核验/禁用清单", "逐页素材映射", "补充责任人"],
    acceptance: ["每项资料有来源和状态", "敏感或版权不明资料被隔离", "没有把 AI 生成内容标为事实"],
    stopConditions: ["公开授权不清楚", "资料包含未脱敏个人信息"],
    fields: [
      {
        id: "materialSummary",
        label: "资料概况",
        description: "说明有哪些资料，不要贴入未脱敏原文。",
        example: "旧官网 8 页、产品表格、20 张已授权照片、5 条客户评价",
        required: true,
        multiline: true,
        sensitiveWarning: true,
      },
      {
        id: "publicationRules",
        label: "公开规则",
        description: "什么可以公开，什么必须审批。",
        example: "价格需运营确认；客户名称未经书面同意不得公开",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["只做盘点，不改写事实", "按来源、日期、所有者、授权和质量分类", "映射到候选页面", "把缺口转成待办"],
  },
  {
    id: "spec-prd",
    title: "Spec / PRD",
    stageIds: [3],
    when: "目标和资料基本清楚，需要让 AI 与人按同一约定工作时。",
    preparation: ["项目简报", "资料来源", "关键约束"],
    deliverables: ["目标和非目标", "用户任务", "范围", "验收标准", "未知项"],
    acceptance: ["每个功能对应用户结果", "非范围明确", "高风险未知项未被猜测"],
    stopConditions: ["目标用户仍未确认", "关键业务规则互相冲突"],
    fields: [
      ...commonProjectFields,
      {
        id: "scope",
        label: "本期范围",
        description: "列出必须完成的用户结果。",
        example: "查看空间、比较套餐、提交预约；不含在线支付",
        required: true,
        multiline: true,
      },
      {
        id: "constraints",
        label: "约束",
        description: "时间、地域、内容、法律、技术或维护约束。",
        example: "中国大陆和全球均可访问；运营可更新价格；两周内出首版",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["先列事实和未知项", "写目标、非目标与用户路径", "把需求写成可观察结果", "为失败和空状态写验收", "提交评审，不直接开始编码"],
  },
  {
    id: "sitemap-content",
    title: "Sitemap 与逐页内容",
    stageIds: [3],
    when: "需要决定有哪些页面、导航如何组织、每页说什么时。",
    preparation: ["用户首要任务", "内容盘点", "搜索需求"],
    deliverables: ["Sitemap", "主导航", "逐页目标、内容和 CTA", "缺失素材"],
    acceptance: ["每页只有一个主要目的", "导航名称是用户语言", "没有无来源的信任内容"],
    stopConditions: ["关键内容缺失且无人负责", "页面只是为了堆关键词"],
    fields: [
      {
        id: "primaryJourneys",
        label: "关键用户路径",
        description: "用户从哪里进入，最终完成什么。",
        example: "搜索进入服务页 → 查看案例 → 预约咨询",
        required: true,
        multiline: true,
      },
      {
        id: "availableContent",
        label: "可用内容",
        description: "列出已确认可公开的材料。",
        example: "服务说明、价格区间、团队照片、地址、常见问题",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["按用户任务分组内容", "先设计最短关键路径", "为每页定义目的、证据、CTA 和来源", "列出可删除的重复页面"],
  },
  {
    id: "stack-adr",
    title: "技术栈与 ADR",
    stageIds: [4],
    when: "已经知道网站类型、维护人和风险，需要选择实现方式时。",
    preparation: ["功能与数据要求", "维护方式", "地域和优先级"],
    deliverables: ["首选、简化、扩展方案", "取舍", "不适用条件", "迁移与回滚影响"],
    acceptance: ["事实与工程判断分开", "中国大陆只是附加约束", "没有用热门程度替代需求"],
    stopConditions: ["支付/权限等高风险边界未定义", "供应商关键能力未从官方文档核验"],
    fields: [
      {
        id: "requirements",
        label: "功能和数据要求",
        description: "列出动态功能、内容更新和数据保存。",
        example: "运营每周改价格；预约表单；不登录；不在线支付",
        required: true,
        multiline: true,
      },
      {
        id: "teamConstraints",
        label: "团队与运营约束",
        description: "谁会维护、是否懂代码、预算与交付周期。",
        example: "一名非技术运营维护内容；开发者按月支持",
        required: true,
        multiline: true,
      },
      {
        id: "regionConstraints",
        label: "地域约束",
        description: "写明主要访问地区及必须验证的服务。",
        example: "中国大陆与海外均访问；第三方字体和分析需替代方案",
        required: false,
      },
    ],
    executionSteps: ["把需求转成技术约束", "分别给出首选、简化和扩展方案", "逐项比较内容维护、安全、成本、迁移和地区可用性", "生成 ADR 并列出待验证假设"],
  },
  {
    id: "design-review",
    title: "设计 Brief 与原型评审",
    stageIds: [4],
    when: "需要让 AI 设计或评审关键页面与流程时。",
    preparation: ["真实内容", "品牌素材", "用户任务", "参考来源"],
    deliverables: ["设计 Brief", "页面状态清单", "评审问题", "修改优先级"],
    acceptance: ["首屏能说明用户下一步", "使用真实内容长度", "移动端和错误状态被设计"],
    stopConditions: ["没有真实内容或视觉目标", "只以个人喜好判断业务流程"],
    fields: [
      {
        id: "designGoal",
        label: "设计目标",
        description: "描述用户完成什么，不只写风格词。",
        example: "让访客在 10 秒内理解空间定位并找到预约入口",
        required: true,
        multiline: true,
      },
      {
        id: "visualReferences",
        label: "视觉依据",
        description: "品牌规范、截图、Figma、现有组件或明确参考。",
        example: "品牌色规范、现有名片、两个已授权参考页面截图",
        required: true,
        multiline: true,
      },
      {
        id: "states",
        label: "必须覆盖的状态",
        description: "桌面、移动、空、错误、加载、成功等。",
        example: "390px 移动端、表单校验错误、提交成功、无网络",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["先复述设计依据", "列出关键页面和状态", "生成或评审原型", "从任务清晰度、可访问性、内容证据和响应式检查", "给出可验证的修改项"],
  },
  {
    id: "vertical-slice",
    title: "垂直切片任务",
    stageIds: [6],
    when: "Spec 已确认，需要把工作拆成小而完整的用户结果时。",
    preparation: ["Spec", "架构边界", "验收命令"],
    deliverables: ["单个切片范围", "依赖", "验收", "回滚点"],
    acceptance: ["一次只交付一个用户结果", "测试接缝明确", "不会顺手重构无关代码"],
    stopConditions: ["切片无法独立验证", "依赖的接口或内容尚未确认"],
    fields: [
      {
        id: "userOutcome",
        label: "本切片用户结果",
        description: "用户完成后能看到什么变化。",
        example: "访客可查看套餐并成功提交预约请求",
        required: true,
        multiline: true,
      },
      {
        id: "boundaries",
        label: "范围与非范围",
        description: "限制本次改动。",
        example: "包含表单 UI、校验和邮件服务适配；不含用户账号",
        required: true,
        multiline: true,
      },
      {
        id: "verification",
        label: "验证方式",
        description: "写命令、页面路径和人工检查。",
        example: "单元测试、构建、390px 表单流程、错误态截图",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["列依赖和风险", "定义最小端到端路径", "先建立失败的验证", "实现最小代码", "验证并记录证据后停止"],
  },
  {
    id: "codex-implementation",
    title: "Codex 实施",
    stageIds: [5, 6],
    when: "任务范围、代码位置和验收标准已经明确时。",
    preparation: ["目标仓库", "相关文件", "Spec/任务", "验证方式"],
    deliverables: ["限定范围内的改动", "验证结果", "风险与未完成项"],
    acceptance: ["保留用户已有改动", "没有扩大授权", "构建和目标测试通过"],
    stopConditions: ["工作区冲突无法安全绕开", "需要新权限或高风险外部写操作"],
    fields: [
      {
        id: "implementationTask",
        label: "要实现的任务",
        description: "引用已确认任务，不要只写“做个网站”。",
        example: "实现首页和预约表单这一垂直切片，按 Spec 第 3.2 节验收",
        required: true,
        multiline: true,
      },
      {
        id: "repoContext",
        label: "仓库与相关上下文",
        description: "目录、规范、相关文件和不能改的区域。",
        example: "遵守 AGENTS.md；修改 src/pages 与表单组件；不改部署配置",
        required: true,
        multiline: true,
      },
      {
        id: "verification",
        label: "验证方式",
        description: "必须执行的测试、构建和浏览器路径。",
        example: "npm test；npm run build；桌面与 390px 完成一次预约",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["先读项目约束和相关文件", "复述假设与改动边界", "按垂直切片实施", "运行验证并修复真实失败", "报告完成、证据和剩余风险"],
  },
  {
    id: "quality-review",
    title: "测试、无障碍与性能审查",
    stageIds: [7],
    when: "功能基本完成，需要证明对真实用户可用时。",
    preparation: ["关键路径", "目标设备", "浏览器与性能目标"],
    deliverables: ["按严重度排序的问题", "复现证据", "通过项和证据限制"],
    acceptance: ["覆盖键盘与 200% 缩放", "区分截图可见风险与需要工具验证的事实", "不宣称截图等于 WCAG 合规"],
    stopConditions: ["无法访问真实流程", "测试环境与上线环境差异未知"],
    fields: [
      {
        id: "criticalFlows",
        label: "关键路径",
        description: "按用户步骤列出。",
        example: "首页 → 套餐 → 预约 → 校验错误 → 提交成功",
        required: true,
        multiline: true,
      },
      {
        id: "targets",
        label: "目标与门槛",
        description: "视口、浏览器、无障碍和性能目标。",
        example: "390px/1440px；键盘；200% 缩放；Core Web Vitals 作为观察指标",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["按流程逐步捕获证据", "检查功能、错误和空状态", "检查响应式、键盘、语义和对比度风险", "测量后再讨论性能", "输出阻塞项和复测清单"],
  },
  {
    id: "debug-review",
    title: "调试与代码评审",
    stageIds: [6, 7],
    when: "出现可复现问题，或准备合并一个切片时。",
    preparation: ["复现步骤", "预期/实际", "日志与最近改动"],
    deliverables: ["最小复现", "根因证据", "修复", "回归测试"],
    acceptance: ["根因与症状分开", "没有随机尝试多个无证据改动", "新增回归保护"],
    stopConditions: ["无法稳定复现且缺少观察数据", "修复需要扩大业务范围"],
    fields: [
      {
        id: "symptom",
        label: "问题与复现",
        description: "写最短步骤、预期和实际。",
        example: "390px 下打开菜单后按 Tab，焦点进入被遮挡的正文链接",
        required: true,
        multiline: true,
      },
      {
        id: "evidence",
        label: "现有证据",
        description: "日志、截图、失败测试或最近变更。",
        example: "失败的键盘测试、DOM 截图、相关提交",
        required: false,
        multiline: true,
        sensitiveWarning: true,
      },
    ],
    executionSteps: ["复现并缩小范围", "提出可证伪假设", "只增加必要观察", "修复根因", "添加回归测试并评审与 Spec 的一致性"],
  },
  {
    id: "release-review",
    title: "发布、回滚与上线复盘",
    stageIds: [8],
    when: "即将上线、灰度发布或刚完成一次发布时。",
    preparation: ["构建产物", "环境差异", "负责人", "监控与回滚入口"],
    deliverables: ["发布清单", "停止/回滚阈值", "监控责任", "复盘行动"],
    acceptance: ["关键配置和数据迁移可核验", "回滚步骤可执行", "上线后有人观察用户结果"],
    stopConditions: ["没有可恢复版本", "生产凭据或责任人缺失", "高风险验收未通过"],
    fields: [
      {
        id: "releaseScope",
        label: "发布范围",
        description: "版本、功能、数据和配置变化。",
        example: "首版官网、预约表单、域名切换；不迁移旧用户数据",
        required: true,
        multiline: true,
      },
      {
        id: "rollbackPlan",
        label: "回滚计划",
        description: "触发条件、负责人、步骤和数据处理。",
        example: "表单成功率异常或 5xx 持续 5 分钟即回滚到上一构建",
        required: true,
        multiline: true,
      },
      {
        id: "monitoringPlan",
        label: "上线观察",
        description: "监控什么、谁观察、观察多久。",
        example: "开发观察错误与延迟 2 小时；运营检查表单和内容 24 小时",
        required: true,
        multiline: true,
      },
    ],
    executionSteps: ["核对所有阻塞 Gate", "确认备份、回滚和责任人", "分阶段发布并观察", "达到停止条件立即回退", "记录事实、影响、根因和改进行动"],
  },
];
